spring:
  mvc:
    web:
      resources:
        add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 12121212!@Qw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update                   # Автоматическое создание/обновление схемы базы данных
    show-sql: true                       # Показ SQL-запросов в консоли
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Указание диалекта для PostgreSQL
  mail:
    host: smtp.gmail.com
    port: 587
    username: helpmeplsmen@gmail.com
    password: qpyz bqmd vkgz cwzh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  # Настройки для управления транзакциями
  transaction:
    default-timeout: 30                  # Тайм-аут транзакции в секундах

# Настройки сервера
server:
  port: 8081                         # Порт, на котором будет запущено приложение



marketplace:
  app:
    secret: q6b+8X0O8zIYFhG4u4n5nJ3hK9x9m9QWm6H6xW9f0uI=
    lifetime: 60000
