spring:
  mvc:
    web:
      resources:
        add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 12121212!@Qw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: helpmeplsmen@gmail.com
    password: qpyz bqmd vkgz cwzh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  transaction:
    default-timeout: 30

# Настройки сервера
server:
  port: 8081

marketplace:
  app:
    secret: q6b+8X0O8zIYFhG4u4n5nJ3hK9x9m9QWm6H6xW9f0uI=
    lifetime: 60000
